#!/usr/bin/env python3
"""Generate docs/FLOORS_BOARD.md — living method × protocol × floor glance (#195).

SoT page: docs/FLOORS_BOARD.md (never hand-edit). Separate from status.html.

Row set (documented source):
  Schema gather/read methods from crude_engine/schemas/*.yaml whose method
  `type:` is dict | list | list_append (same READ_TYPES as generate_catalog.py).
  Keys present only in tests/fixtures/offline_gold/gold_floors.json are unioned
  in so catalogue floors are never silently dropped if a schema hole appears.

Stub honesty (Architect #195 — gold = device-proved only):
  Today's gold_floors.json is sanitized schema-shaped sample (see its
  description). Presence in that file is NOT a floor until Test wires a
  device-proved / HITL-gold provenance flag. Therefore this stub sets
  floor_source=no-floor for every row and leaves offline/mops/snmp/ssh as
  untested. Do not invent floors from sanitized XML. No lab IPs.

  Optional offline fill from tests/offline_gold_matrix.py is deferred: that
  harness needs napalm/OfflineHIOS and must not be treated as floor provenance.
  Test wiring follow-up will feed real cell enums.

Cell enum: pass | fail | untested | no-floor | empty (optional)

    python3 scripts/generate_floors_board.py          # write docs/FLOORS_BOARD.md
    python3 scripts/generate_floors_board.py --check  # fail if generated file stale
"""
from __future__ import annotations

import argparse
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("pyyaml required\n")
    sys.exit(2)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCHEMAS = os.path.join(ROOT, "crude_engine", "schemas")
GOLD = os.path.join(ROOT, "tests", "fixtures", "offline_gold", "gold_floors.json")
OUT = os.path.join(ROOT, "docs", "FLOORS_BOARD.md")

READ_TYPES = {"dict", "list", "list_append"}
COLUMNS = ("method", "floor_source", "offline", "mops", "snmp", "ssh")
CELL_ENUM = ("pass", "fail", "untested", "no-floor", "empty")


def load_yaml(path: str):
    with open(path) as f:
        return yaml.safe_load(f) or {}


def schema_read_methods() -> list[str]:
    """Gather/read method names from schemas (typed dict|list|list_append)."""
    names: set[str] = set()
    if not os.path.isdir(SCHEMAS):
        return []
    for fname in sorted(os.listdir(SCHEMAS)):
        if not fname.endswith(".yaml"):
            continue
        data = load_yaml(os.path.join(SCHEMAS, fname))
        if not isinstance(data, dict):
            continue
        methods = data.get("methods") or {}
        if not isinstance(methods, dict):
            continue
        for name, mdef in methods.items():
            if not isinstance(mdef, dict):
                continue
            if mdef.get("type") in READ_TYPES:
                names.add(str(name))
    return sorted(names)


def gold_method_keys() -> list[str]:
    """Method keys from gold_floors.json (sanitized sample — not device-proved)."""
    if not os.path.isfile(GOLD):
        return []
    with open(GOLD) as f:
        data = json.load(f)
    methods = data.get("methods") if isinstance(data, dict) else None
    if not isinstance(methods, dict):
        return []
    return sorted(str(k) for k in methods.keys())


def row_methods() -> list[str]:
    return sorted(set(schema_read_methods()) | set(gold_method_keys()))


def render(methods: list[str]) -> str:
    lines: list[str] = []
    lines.append("# FLOORS_BOARD")
    lines.append("")
    lines.append(
        "> Auto-generated by `scripts/generate_floors_board.py`. **Do not edit.**"
    )
    lines.append(
        "> Effort companion: [#195](https://github.com/AdamRickards/crude-engine/issues/195). "
        "Glance chart: `local/agents/diagrams/effort-board.md`."
    )
    lines.append("")
    lines.append("## Stub note — Test provenance wiring follow-up")
    lines.append("")
    lines.append(
        "Architect rule: **floor** means MOPS gather proved from an end device "
        "(device-proved / HITL gold), not sanitized-only invent."
    )
    lines.append("")
    lines.append(
        "`tests/fixtures/offline_gold/gold_floors.json` today is sanitized "
        "schema-shaped sample. This stub therefore sets `floor_source=no-floor` "
        "for all rows and leaves protocol cells `untested` until Test feeds "
        "device-proved provenance and honest offline/mops/snmp/ssh aggregates "
        "(no lab identity in this page)."
    )
    lines.append("")
    lines.append("### Cell vocabulary")
    lines.append("")
    lines.append("| value | meaning |")
    lines.append("| --- | --- |")
    lines.append("| `pass` | meets floor / matrix green |")
    lines.append("| `fail` | compare red vs floor |")
    lines.append("| `untested` | no honest signal yet |")
    lines.append("| `no-floor` | no device-proved floor |")
    lines.append("| `empty` | optional — both sides empty look-into |")
    lines.append("")
    lines.append("### Row source")
    lines.append("")
    lines.append(
        f"Schema typed reads (`type:` in `{', '.join(sorted(READ_TYPES))}`) "
        f"union `gold_floors.json` method keys. "
        f"Rows: **{len(methods)}**."
    )
    lines.append("")
    lines.append("## Glance")
    lines.append("")
    lines.append("| " + " | ".join(COLUMNS) + " |")
    lines.append("| " + " | ".join("---" for _ in COLUMNS) + " |")
    for method in methods:
        cells = [
            f"`{method}`",
            "`no-floor`",
            "`untested`",
            "`untested`",
            "`untested`",
            "`untested`",
        ]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "Regenerate: `python3 scripts/generate_floors_board.py`. "
        "Stale check: `python3 scripts/generate_floors_board.py --check` "
        "(wired in `scripts/ci_offline.sh`)."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate docs/FLOORS_BOARD.md (floors glance stub, #195)"
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/FLOORS_BOARD.md is missing or stale",
    )
    args = p.parse_args()

    methods = row_methods()
    if not methods:
        print("FAIL  no gather methods found (schemas / gold_floors)")
        return 1
    text = render(methods)
    rel = os.path.relpath(OUT, ROOT)
    print(f"floors board rows={len(methods)} enum={','.join(CELL_ENUM)}")

    if args.check:
        if not os.path.isfile(OUT):
            print(f"FAIL  missing {rel}; re-run scripts/generate_floors_board.py")
            return 1
        on_disk = open(OUT).read()
        if on_disk != text:
            print(f"FAIL  {rel} is stale; re-run scripts/generate_floors_board.py")
            return 1
        print(f"PASS  {rel} matches generator")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
