#!/usr/bin/env python3
"""Render docs/status.html from local/agents Destination + Effort board.

No v1 program cycles. Destination lives in local/agents/README.md.
Effort progress lives in local/agents/diagrams/effort-board.md.

    python3 scripts/generate_status.py
    python3 scripts/generate_status.py --check   # fail if agents law files missing
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "docs", "status.html")

# Agents / Effort law (v1 program files removed).
REQUIRED = (
    "local/agents/README.md",
    "local/agents/diagrams/effort-board.md",
    "local/agents/1.17-clerk/INSTRUCTIONS.md",
    "docs/ROADMAP.md",
)


def esc(s):
    return html.escape("" if s is None else str(s))


def read_text(rel):
    path = os.path.join(ROOT, rel)
    with open(path, encoding="utf-8") as f:
        return f.read()


def effort_rows(md: str):
    """Parse the Live bubbles table from effort-board.md (best-effort)."""
    rows = []
    in_live = False
    for line in md.splitlines():
        if line.startswith("## Live bubbles"):
            in_live = True
            continue
        if in_live and line.startswith("## "):
            break
        if not in_live or not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 3:
            continue
        if cells[0].lower() in ("bubble", "---") or set(cells[0]) <= {"-"}:
            continue
        rows.append(cells[:3])
    return rows


def render(effort_md: str):
    now = dt.date.today().isoformat()
    rows = effort_rows(effort_md)
    tbody = []
    for bubble, status, children in rows:
        tbody.append(
            "<tr>"
            f"<td>{esc(re.sub(r'\*\*', '', bubble))}</td>"
            f"<td>{esc(re.sub(r'\*\*', '', status))}</td>"
            f"<td class='mono'>{esc(re.sub(r'\*\*', '', children))}</td>"
            "</tr>"
        )
    table_body = "".join(tbody) or (
        "<tr><td colspan='3'>Open local/agents/diagrams/effort-board.md</td></tr>"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>crude-engine — agents status</title>
<style>
:root {{
  --bg:#0b0d12; --panel:#151922; --border:#2a3142; --text:#e8ecf4;
  --muted:#8b93a7; --accent:#5b9dff;
  --font:"IBM Plex Sans","Segoe UI",system-ui,sans-serif;
  --mono:"IBM Plex Mono",ui-monospace,monospace;
}}
* {{ box-sizing:border-box; }}
html,body {{ margin:0; background:var(--bg); color:var(--text); font-family:var(--font); }}
.wrap {{ max-width:1040px; margin:0 auto; padding:28px 20px 72px; }}
h1 {{ margin:0 0 6px; font-size:26px; }}
h2 {{ margin:32px 0 12px; font-size:12px; letter-spacing:.14em; text-transform:uppercase; color:var(--muted); }}
.kicker {{ font-family:var(--mono); font-size:11px; color:var(--muted); letter-spacing:.12em; text-transform:uppercase; }}
.lede {{ font-size:16px; color:#d5dae6; }}
.card {{ background:var(--panel); border:1px solid var(--border); border-radius:10px; padding:16px 18px; }}
table {{ width:100%; border-collapse:collapse; background:var(--panel); border:1px solid var(--border); }}
th,td {{ text-align:left; padding:8px 10px; border-bottom:1px solid var(--border); font-size:13px; vertical-align:top; }}
th {{ color:var(--muted); font-weight:500; font-size:11px; text-transform:uppercase; letter-spacing:.08em; }}
.mono {{ font-family:var(--mono); font-size:12px; }}
a {{ color:var(--accent); }}
footer {{ margin-top:36px; color:var(--muted); font-family:var(--mono); font-size:11px; }}
</style>
</head>
<body>
<div class="wrap">
  <p class="kicker">crude-engine · generated {esc(now)}</p>
  <h1>Destination + Effort</h1>
  <p class="lede">Process law and Destination live in <strong>local/agents/</strong>.
  Status is Effort/agents-honest — not v1 cycles.</p>

  <h2>How this works</h2>
  <div class="card">
    <p>Destination + Rules → Effort board → named proofs → GitHub leftovers.
    Brain is the repo. GitHub is the host.</p>
    <p class="mono">
      <a href="../local/agents/README.md">local/agents/README.md</a> ·
      <a href="../local/agents/diagrams/effort-board.md">effort-board.md</a> ·
      <a href="ROADMAP.md">ROADMAP.md</a> ·
      <a href="https://github.com/AdamRickards/crude-engine/issues">GitHub issues</a>
    </p>
  </div>

  <h2>Live Effort bubbles</h2>
  <table>
    <thead><tr><th>bubble</th><th>status</th><th>children</th></tr></thead>
    <tbody>{table_body}</tbody>
  </table>

  <footer>
    Regenerated by scripts/generate_status.py. Do not edit this file.
    Offline proofs: scripts/ci_offline.sh
  </footer>
</div>
</body>
</html>
"""


def check_human_files():
    missing = []
    for rel in REQUIRED:
        if not os.path.isfile(os.path.join(ROOT, rel)):
            missing.append(rel)
    return missing


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    missing = check_human_files()
    if args.check and missing:
        print("FAIL  missing agents/Effort files:")
        for m in missing:
            print(f"  {m}")
        return 1
    effort_md = read_text("local/agents/diagrams/effort-board.md")
    html_out = render(effort_md)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html_out)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    if args.check:
        print("PASS  agents/Effort files present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
